### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ViacheslavZyrianov** [backrunner/vue-virtual-masonry#1]
So i use it like that:
```
<VirtualMasonry
    :items="subscribersMocked"
    cols="3"
    :col-width="100"
    :item-height-getter="heightGetter"
  >
  <template #default="item">
    <h1>text</h1>
  </template>
</VirtualMasonry>
```

With the only difference in defining default slot. In provided example it is `slot-scope="props"`, but it doesn't work like this now.

In heightGetter i have literally the same, that is in example:

```
heightGetter(item) {
  return item.height;
}
```

And no results. No error or something, just blank page.

**Comment by backrunner** [comment]
Sorry for the late reply. This lib is based on Vue 2, if you're using it on Vue 3, there may be some issues.
Which version of Vue you're using now? If you're using Vue 3, you can take a look at our another project called `anyui`, this lib has been contained and it's based on Vue 3.

https://github.com/any-design/anyui/blob/main/src/packages/masonry/AMasonry.vue

⬆️ Here's the project.

You can use it by
```js
import { Masonry } from '@any-design/anyui';

app.use(Masonry);
```

If you're using Vue 2, I think it should work right. I'll take a further look later.

**Comment by ViacheslavZyrianov** [comment]
@backrunner i am using Vue2.

**Comment by backrunner** [comment]
> @backrunner i am using Vue2.

I've checked my demo in this project, it works right. And I found that the only reason you saw nothing on the page is the `heightGetter` returned `undefined`.

The `heightGetter` should return a number which means the height of a certain cell. I'll enhance my document later. The `item` is actually the item in the array you passed to the `items` property.

BTW: The right property name is `col`, not `cols`, the value should be a number.

**Comment by ViacheslavZyrianov** [comment]
@backrunner currently i am passing the prop item-height-getter this way: `:item-height-getter="heightGetter"`
And it is simply computed prop that returns number 301. I don't have any info about item's height, so i can pass only like that. And after passing i receive and error **Invalid prop: type check failed for prop "itemHeightGetter". Expected Function, got Number with value 301.**

**Comment by ViacheslavZyrianov** [comment]
@backrunner so, eventually, i made it work! But, i had to transform the incoming list from format:
`[123,234,345]` to `[
  {
    data: 123,
    height: 301
  },
  {
    data: 234,
    height: 301
  },
  {
    data: 345,
    height: 301
  }
]`

But, due to fixed height, when i try to change one of the masonry item's height, it just overlaps the element below, instead of moving it below a bit, like regular masonry does.

**Comment by backrunner** [comment]
> @backrunner currently i am passing the prop item-height-getter this way: `:item-height-getter="heightGetter"` And it is simple method that returns number 301. I don't have any info about item's height, so i can pass only like that. And after passing i receive and error **Invalid prop: type check failed for prop "itemHeightGetter". Expected Function, got Number with value 301.**

```vue
<template>
  <div class="container">
    <VirtualMasonry :items="items" :col="10" :colWidth="100" :itemHeightGetter="heightGetter">
      <template>
        <h1>text</h1>
      </template>
    </VirtualMasonry>
  </div>
</template>

<script>
export default {
  data() {
    return {
      items: [],
    };
  },
  created() {
    // generate items
    const items = new Array(30000).fill(1).map(() => ({}));
    this.$set(this, 'items', items);
  },
  methods: {
    heightGetter(item) {
      return 301;
    },
  },
};
</script>
```

↑ This code works right. You should pass a true `function` to `itemHeightGetter`, if you passed a `computed`, it will be treated as a number.

**Comment by backrunner** [comment]
> @backrunner so, eventually, i made it work! But, i had to transform the incoming list from format: `[123,234,345]` to `[ { data: 123, height: 301 }, { data: 234, height: 301 }, { data: 345, height: 301 } ]`
> 
> But, due to fixed height, when i try to change one of the masonry item's height, it just overlaps the element below, instead of moving it below a bit, like regular masonry does.

Due to the performance issue, masonry will not watch all the properties of the certain `item` in the `items` array, if you want to change the height of some item, you need to change it first and set the whole `items` array to the property again.

For example, if you bound an array named `items`, you need to this:

```js
<VirutalMasonry :items="items" />

// in the script scope
items[0].height = 200;
this.$set(this, 'items', items); // it's better to use `this.$set` to trigger re-calculation or make things in the items to be reactive

// or

this.items = [...this.items]; // just for triggering the watcher of Vue
```

**Comment by backrunner** [comment]
Issue closed due to no new comment for 10 days. It's welcome to create a new one if you meet any problem.
